apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: mr0022/avtoalert:latest
        env:
          - name: MYSQL_URL
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_URL
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USERNAME
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /app1/liveliness
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /app1/readiness
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
      - port: 8000