# Generated by Django 4.1.4 on 2022-12-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('veljavnost', models.DateField()),
            ],
        ),
    ]
