# Generated by Django 4.1.4 on 2022-12-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='opis',
            field=models.CharField(default='', max_length=255),
        ),
    ]
