# Generated by Django 4.1.4 on 2022-12-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_users_ime_users_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('filterID', models.AutoField(primary_key=True, serialize=False)),
                ('znamka', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('cena_od', models.IntegerField()),
                ('cena_do', models.IntegerField()),
                ('letnik_od', models.IntegerField()),
                ('letnik_do', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.users')),
            ],
        ),
    ]
