# Generated by Django 4.1.4 on 2022-12-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='znamka',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
