# Generated by Django 4.1.4 on 2022-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_filters_znamka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='znamka',
            field=models.CharField(default='', max_length=255),
        ),
    ]
