# Generated by Django 4.1.4 on 2022-12-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_avti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
