# Generated by Django 4.1.4 on 2022-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_users_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regkode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('koda', models.IntegerField()),
                ('opis', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
