# Generated by Django 4.1.4 on 2022-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_regkode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avti',
            name='carID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
