# Generated by Django 4.1.4 on 2022-12-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_avti_carid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
