# Generated by Django 4.1.4 on 2022-12-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_filters_cena_do_alter_filters_cena_od_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='cena_do',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='cena_od',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='letnik_do',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='letnik_od',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filters',
            name='znamka',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
